#!/bin/bash -i
# firstlogin for cceckman. Set up home, etc.
# This should mostly / probably work on platforms other than Arch.

pushd $HOME # Make sure we have a good point of reference.

# TODO Make sure active SSH credentials work for Github; prompt to make new ones
# or not depending.

# Tilde repository gets special treatment.
git clone git@github.com:cceckman/Tilde.git Tilde && mv Tilde/.git . && rm -rf Tilde && git reset --hard

# CLONE REPOSITORIES
# Copy down repositories I like, into go-compatible locations,
# and link them to shorter paths.
GH_REPOS="cceckman/cce3 cceckman/distro cceckman/cceckman.github.io"
GH_PREFIX="$HOME/src/github.com"
mkdir -p $GH_PREFIX
mkdir $HOME/r
for repo in $GH_REPOS
do
  REPOPATH="${GH_PREFIX}/${repo}"
  git clone "git@github.com:${repo}" "$REPOPATH" \
    && ln -s "$HOME/r/$( basename $REPOPATH )"
done
# DONE

popd # $HOME
