#!/bin/bash
# Ambroix for GCE
# Started on the first boot of the machine, as root.

# Collect plugins
f=common/depend.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
f=common/kvpf.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
f=common/err.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }

f=platforms/gce/helpers.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }

# Install packages as root
cat users/$TGT_USER/pkgs | xargs pacman --noconfirm -S

# Set locale settings
ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
sed -i 's/^#en_US/en_US/' /etc/locale.gen && locale-gen
echo LANG=en_US > /etc/locale.conf
# OK with default elsewhere

# Start the firstlogin script on login.
TGT_HOME=$(su -c 'echo $HOME' "$TGT_USER")
cat <<EOF >$TGT_HOME/.profile
#!/bin/sh
pushd $PWD
users/$TGT_USER/firstlogin >\$HOME/firstlogin.log 2>&1 && \
  $TGT_HOME/.profile
popd
EOF
chmod +x $TGT_HOME/.profile
chown ${TGT_USER}:${TGT_USER} $TGT_HOME/.profile

# Clear bash_profile.
rm $TGT_HOME/.bash_profile
