#!/bin/bash -i
# firstlogin for cceckman. Set up home, etc.
# This should mostly / probably work on platforms other than Arch.

pushd $HOME # Make sure we have a good point of reference.

out=firstlogin.log

# TODO Make sure active SSH credentials work for Github; prompt to make new ones
# or not depending.

# Tilde repository gets special treatment.
(git clone git@github.com:cceckman/Tilde.git Tilde >$out 2>&1 || exit $? ) && \
  mv Tilde/.git . && rm -rf Tilde && git reset --hard

# CLONE REPOSITORIES
# Copy down repositories I like / I own.
GH_REPOS="cceckman/cce3 cceckman/web cceckman/distro cceckman/cceckman.github.io ccontavalli/ssh-ident"

GH_PREFIX="$HOME/r"
GO_PREFIX="$HOME/go" # Keep in sync with Tilde/.bashrc
mkdir -p $GH_PREFIX
mkdir -p $GO_PREFIX

ret=0

for repo in $GH_REPOS
do
  REPOPATH="${GH_PREFIX}/${repo}"
  git clone "git@github.com:${repo}" "$REPOPATH"
  ret=$(($ret + $?))
  # Support Go directory structure. Assume $HOME/go is in $GOPATH.
  GOTOOLPATH="$GO_PREFIX/src/github.com/${repo}"
  mkdir -p $(dirname $GOTOOLPATH) && ln -s $REPOPATH $GOTOOLPATH
done
# DONE

# Use ssh-ident instead of `ssh`.
ln -s $GH_PREFIX/ccontavalli/ssh-ident/ssh-ident $HOME/scripts/ssh 

# My magic for a random list of lowercase characters:
# python -c 'import random; import string; ls = list(string.ascii_lowercase); random.shuffle(ls); print("".join(ls))'
s='pmwrovsxncbtlqgdejiyahkzuf'
a='abcdefghijklmnopqrstuvwxyz'
git config --global user.email $(echo 'wxpjtoi@wwowblpq.wgl' | tr $s $a)
# Yes; just obfuscated, not encrypted.
git config --global user.name "Charles Eckman"
git config --global core.editor "vim"
git config --global diff.tool "meld"

popd # $HOME

exit $?
