#!/bin/bash -i
# firstlogin for cceckman. Set up home, etc.
# This should mostly / probably work on platforms other than Arch.

pushd $HOME # Make sure we have a good point of reference.

out=firstlogin.log

# TODO Make sure active SSH credentials work for Github; prompt to make new ones
# or not depending.

# Tilde repository gets special treatment.
(git clone git@github.com:cceckman/Tilde.git Tilde >$out 2>&1 || exit $? ) && \
  mv Tilde/.git . && rm -rf Tilde && git reset --hard

# And then use the acquired script to get the latest.
scripts/update-repos || exit $?


# My magic for a random list of lowercase characters:
# python -c 'import random; import string; ls = list(string.ascii_lowercase); random.shuffle(ls); print("".join(ls))'
s='pmwrovsxncbtlqgdejiyahkzuf'
a='abcdefghijklmnopqrstuvwxyz'
git config --global user.email $(echo 'wxpjtoi@wwowblpq.wgl' | tr $s $a)
# Yes; just obfuscated, not encrypted.
git config --global user.name "Charles Eckman"
git config --global core.editor "vim"
git config --global diff.tool "meld"

popd # $HOME

exit $?
