#!/bin/bash -i

USER='cceckman' # Yep, overriding a builtin. Deal with it.

echo "Prompting for user $USER's information..."
promptfile="$1"
echo "Storing in promptfile $promptfile."


# Collect plugins
f=common/depend.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
f=common/yesno.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
f=common/kvpf.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
f=common/prompt.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
f=common/err.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }

# Module for asking about key additions.
f=common/keys/prompt; source $f || { >&2 echo "$f not found!" && exit 2; }
# Use corresponding common/keys hooks later to unpack.

# TODO: Recover and verify information from an existing promptfile.
